namespace Medify.Resources.Enums;

public enum SpecialityEnum{
    Anesthesiology,
    Cardiology,
    Dermatology,
    Endocrinology,
    Gastroenterology,
    Geriatrics,
    Hematology,
    Nephrology,
    Neurology,
    Gynecology,
    Oncology,
    Ophthalmology,
    Orthopedics,
    Otolaryngology,
    Pediatrics,
    Rehabilitation,
    Psychiatry,
    Pulmonology,
    Radiology,
    Rheumatology,
    Surgery,
    Neurosurgery,
    Urology,
    Allergolog,
    Neonatology,
    Pediatric_Cardiology,
}